const alphabets = [
  { cyrillic: 'Аа', normal: 'a' },
  { cyrillic: 'Бб', normal: 'b' },
  { cyrillic: 'Вв', normal: 'v' },
  { cyrillic: 'Гг', normal: 'g' },
  { cyrillic: 'Дд', normal: 'd' },
  { cyrillic: 'Ее', normal: 'e' },
  { cyrillic: 'Ёё', normal: 'io' },
  { cyrillic: 'Жж', normal: 'zh' },
  { cyrillic: 'Зз', normal: 'z' },
  { cyrillic: 'Ии', normal: 'i' },
  { cyrillic: 'Йй', normal: 'y' },
  { cyrillic: 'Кк', normal: 'k' },
  { cyrillic: 'Лл', normal: 'l' },
  { cyrillic: 'Мм', normal: 'm' },
  { cyrillic: 'Нн', normal: 'n' },
  { cyrillic: 'Оо', normal: 'o' },
  { cyrillic: 'Пп', normal: 'p' },
  { cyrillic: 'Рр', normal: 'r' },
  { cyrillic: 'Сс', normal: 's' },
  { cyrillic: 'Тт', normal: 't' },
  { cyrillic: 'Уу', normal: 'u' },
  { cyrillic: 'Фф', normal: 'f' },
  { cyrillic: 'Хх', normal: 'kh' },
  { cyrillic: 'Цц', normal: 'ts' },
  { cyrillic: 'Чч', normal: 'ch' },
  { cyrillic: 'Шш', normal: 'sh' },
  { cyrillic: 'Щщ', normal: 'shch' },
  // { cyrillic: 'Ъъ', normal: '' },
  { cyrillic: 'Ыы', normal: 'y' },
  // { cyrillic: 'Ьь', normal: '' },
  { cyrillic: 'Ээ', normal: 'e' },
  { cyrillic: 'Юю', normal: 'iu' },
  { cyrillic: 'Яя', normal: 'ia' }
];

export default alphabets;
